{
    LISTEN_PROMPT : 'Listen to these animals.',
    CHOICES : [
        {visual : '<img class="animal" src="${images}animals/dog.png" />', speech : 'dog'},
        {visual : '<img class="animal" src="${images}animals/cat.png" />', speech : 'cat'},
        {visual : '<img class="animal" src="${images}animals/cow.png" />', speech : 'cow'},
        {visual : '<img class="animal" src="${images}animals/squirrel.png" />', speech : 'squirrel'},
        {visual : '<img class="animal" src="${images}animals/turtle.png" />', speech : 'turtle'},
        {visual : '<img class="animal" src="${images}animals/giraffe.png" />', speech : 'giraffe'},
        {visual : '<img class="animal" src="${images}animals/elephant.png" />', speech : 'elephant'},
        {visual : '<img class="animal" src="${images}animals/bear.png" />', speech : 'bear'},
        {visual : '<img class="animal" src="${images}animals/whale.png" />', speech : 'whale'},
        {visual : '<img class="animal" src="${images}animals/ladybug.png" />', speech : 'ladybug'},
        {visual : '<img class="animal" src="${images}animals/owl.png" />', speech : 'owl'},
        {visual : '<img class="animal" src="${images}animals/mouse.png" />', speech : 'mouse'},
        {visual : '<img class="animal" src="${images}animals/goat.png" />', speech : 'goat'},
        {visual : '<img class="animal" src="${images}animals/llama.png" />', speech : 'llama'},
        {visual : '<img class="animal" src="${images}animals/rabbit.png" />', speech : 'rabbit'},
        {visual : '<img class="animal" src="${images}animals/alligator.png" />', speech : 'alligator'},
        {visual : '<img class="animal" src="${images}animals/leopard.png" />', speech : 'leopard'},
        {visual : '<img class="animal" src="${images}animals/hippo.png" />', speech : 'hippo'},
        {visual : '<img class="animal" src="${images}animals/rhino.png" />', speech : 'rhino'},
        {visual : '<img class="animal" src="${images}animals/zebra.png" />', speech : 'zebra'},
        {visual : '<img class="animal" src="${images}animals/lion.png" />', speech : 'lion'},
        {visual : '<img class="animal" src="${images}animals/kangaroo.png" />', speech : 'kangaroo'},
        {visual : '<img class="animal" src="${images}animals/penguin.png" />', speech : 'penguin'},
    ]
}