{
    LISTEN_PROMPT : 'Listen to these animals.',
    CHOICES : [
        {visual : '<img class="animal" src="${images}animals/dog.png" />', 
         speech : 'dog', 
         sound : '${sounds}animals/4912__NoiseCollector__barks.mp3'},
        {visual : '<img class="animal" src="${images}animals/cat.png" />', 
         speech : 'cat',
         sound: '${sounds}animals/4914__NoiseCollector__cat2.mp3'},
        {visual : '<img class="animal" src="${images}animals/cow.png" />', 
         speech : 'cow',
         sound : '${sounds}animals/16568__acclivity__TwoCows.mp3'},
        {visual : '<img class="animal" src="${images}animals/squirrel.png" />', 
         speech : 'squirrel'},
        {visual : '<img class="animal" src="${images}animals/turtle.png" />', 
         speech : 'turtle'},
        {visual : '<img class="animal" src="${images}animals/giraffe.png" />', 
         speech : 'giraffe'},
        {visual : '<img class="animal" src="${images}animals/elephant.png" />', 
         speech : 'elephant'},
        {visual : '<img class="animal" src="${images}animals/bear.png" />', 
         speech : 'bear',
         sound: '${sounds}animals/70333__mrbubble110__bear_roar.mp3'},
        {visual : '<img class="animal" src="${images}animals/whale.png" />', 
         speech : 'whale'},
        {visual : '<img class="animal" src="${images}animals/ladybug.png" />', 
         speech : 'ladybug'},
        {visual : '<img class="animal" src="${images}animals/owl.png" />', 
         speech : 'owl',
         sound : '${sounds}animals/20684__Johnc__Owl.mp3'},
        {visual : '<img class="animal" src="${images}animals/mouse.png" />', 
         speech : 'mouse'},
        {visual : '<img class="animal" src="${images}animals/goat.png" />', 
         speech : 'goat',
         sound : '${sounds}animals/57794__reinsamba__1202_goat.mp3'},
        {visual : '<img class="animal" src="${images}animals/llama.png" />', 
         speech : 'llama'},
        {visual : '<img class="animal" src="${images}animals/rabbit.png" />', 
         speech : 'rabbit'},
        {visual : '<img class="animal" src="${images}animals/alligator.png" />', 
         speech : 'alligator'},
        {visual : '<img class="animal" src="${images}animals/leopard.png" />', 
         speech : 'leopard'},
        {visual : '<img class="animal" src="${images}animals/hippo.png" />', 
         speech : 'hippo'},
        {visual : '<img class="animal" src="${images}animals/rhino.png" />', 
         speech : 'rhino'},
        {visual : '<img class="animal" src="${images}animals/zebra.png" />', 
         speech : 'zebra'},
        {visual : '<img class="animal" src="${images}animals/lion.png" />', 
         speech : 'lion', sound : '${sounds}animals/63668__Miselaineous__elaine_growl.wav'},
        {visual : '<img class="animal" src="${images}animals/kangaroo.png" />', 
         speech : 'kangaroo'},
        {visual : '<img class="animal" src="${images}animals/penguin.png" />', 
         speech : 'penguin',
         sound : '${sounds}animals/45394__NOISE.INC__pinguin_vox.mp3'}
    ]
}