{
    LISTEN_PROMPT : 'Listen to these animals.',
    CHOICES : [
        {visual : '', speech : 'Maine'},
        {visual : '', speech : 'New Hampshire'},
        {visual : '', speech : 'Vermont'},
        {visual : '', speech : 'New York'},
        {visual : '', speech : 'Massachusetts'},
        {visual : '', speech : 'Rhode Island'},
        {visual : '', speech : 'Connecticut'},
        {visual : '', speech : 'Pennsylvania'},
        {visual : '', speech : 'Deleware'},
        {visual : '', speech : 'Maryland'},
        {visual : '', speech : 'Virginia'},
        {visual : '', speech : 'North Carolina'},
        {visual : '', speech : 'South Carolina'},
        {visual : '', speech : 'Georgia'},
        {visual : '', speech : 'Florida'},
        {visual : '', speech : 'Mississippi'},
        {visual : '', speech : 'Alabama'},
        {visual : '', speech : 'Louisiana'},
        {visual : '', speech : 'Arkansas'},
        {visual : '', speech : 'Tennessee'},
        {visual : '', speech : 'Kentucky'},
        {visual : '', speech : 'West Virginia'},
        {visual : '', speech : 'Ohio'},
        {visual : '', speech : 'Indiana'},
        {visual : '', speech : 'Illinois'},
        {visual : '', speech : 'Michigan'},
        {visual : '', speech : 'Wisconsin'},
        {visual : '', speech : 'Iowa'},
        {visual : '', speech : 'Nebraska'},
        {visual : '', speech : 'Kansas'},
        {visual : '', speech : 'Texas'},
        {visual : '', speech : 'North Dakota'},
        {visual : '', speech : 'South Dakota'},
        {visual : '', speech : 'Montana'},
        {visual : '', speech : 'Wyoming'},
        {visual : '', speech : 'Colorado'},
        {visual : '', speech : 'Nevada'},
        {visual : '', speech : 'Idaho'},
        {visual : '', speech : 'California'},
        {visual : '', speech : 'Oregon'},
        {visual : '', speech : 'Washington'},
        {visual : '', speech : 'Alaska'},
        {visual : '', speech : 'Hawaii'},
        {visual : '', speech : 'Oklahoma'},
        {visual : '', speech : 'Utah'},
        {visual : '', speech : 'New Mexico'},
        {visual : '', speech : 'Arizona'},
        {visual : '', speech : 'Missouri'},
        {visual : '', speech : 'New Jersey'},
        {visual : '', speech : 'Minnesota'}
    ]
}