{
    LISTEN_PROMPT : 'Listen to these states.',
    CHOICES : [
        {visual : '<img class="state" src="${images}states/ME.png" />', speech : 'Maine'},
        {visual : '<img class="state" src="${images}states/NH.png" />', speech : 'New Hampshire'},
        {visual : '<img class="state" src="${images}states/VT.png" />', speech : 'Vermont'},
        {visual : '<img class="state" src="${images}states/NY.png" />', speech : 'New York'},
        {visual : '<img class="state" src="${images}states/MA.png" />', speech : 'Massachusetts'},
        {visual : '<img class="state" src="${images}states/RI.png" />', speech : 'Rhode Island'},
        {visual : '<img class="state" src="${images}states/CT.png" />', speech : 'Connecticut'},
        {visual : '<img class="state" src="${images}states/PA.png" />', speech : 'Pennsylvania'},
        {visual : '<img class="state" src="${images}states/DE.png" />', speech : 'Deleware'},
        {visual : '<img class="state" src="${images}states/MD.png" />', speech : 'Maryland'},
        {visual : '<img class="state" src="${images}states/VA.png" />', speech : 'Virginia'},
        {visual : '<img class="state" src="${images}states/NC.png" />', speech : 'North Carolina'},
        {visual : '<img class="state" src="${images}states/SC.png" />', speech : 'South Carolina'},
        {visual : '<img class="state" src="${images}states/GA.png" />', speech : 'Georgia'},
        {visual : '<img class="state" src="${images}states/FL.png" />', speech : 'Florida'},
        {visual : '<img class="state" src="${images}states/MS.png" />', speech : 'Mississippi'},
        {visual : '<img class="state" src="${images}states/AL.png" />', speech : 'Alabama'},
        {visual : '<img class="state" src="${images}states/LA.png" />', speech : 'Louisiana'},
        {visual : '<img class="state" src="${images}states/AR.png" />', speech : 'Arkansas'},
        {visual : '<img class="state" src="${images}states/TN.png" />', speech : 'Tennessee'},
        {visual : '<img class="state" src="${images}states/KY.png" />', speech : 'Kentucky'},
        {visual : '<img class="state" src="${images}states/WV.png" />', speech : 'West Virginia'},
        {visual : '<img class="state" src="${images}states/OH.png" />', speech : 'Ohio'},
        {visual : '<img class="state" src="${images}states/IN.png" />', speech : 'Indiana'},
        {visual : '<img class="state" src="${images}states/IL.png" />', speech : 'Illinois'},
        {visual : '<img class="state" src="${images}states/MI.png" />', speech : 'Michigan'},
        {visual : '<img class="state" src="${images}states/WI.png" />', speech : 'Wisconsin'},
        {visual : '<img class="state" src="${images}states/IA.png" />', speech : 'Iowa'},
        {visual : '<img class="state" src="${images}states/NE.png" />', speech : 'Nebraska'},
        {visual : '<img class="state" src="${images}states/KS.png" />', speech : 'Kansas'},
        {visual : '<img class="state" src="${images}states/TX.png" />', speech : 'Texas'},
        {visual : '<img class="state" src="${images}states/ND.png" />', speech : 'North Dakota'},
        {visual : '<img class="state" src="${images}states/SD.png" />', speech : 'South Dakota'},
        {visual : '<img class="state" src="${images}states/MT.png" />', speech : 'Montana'},
        {visual : '<img class="state" src="${images}states/WY.png" />', speech : 'Wyoming'},
        {visual : '<img class="state" src="${images}states/CO.png" />', speech : 'Colorado'},
        {visual : '<img class="state" src="${images}states/NV.png" />', speech : 'Nevada'},
        {visual : '<img class="state" src="${images}states/ID.png" />', speech : 'Idaho'},
        {visual : '<img class="state" src="${images}states/CA.png" />', speech : 'California'},
        {visual : '<img class="state" src="${images}states/OR.png" />', speech : 'Oregon'},
        {visual : '<img class="state" src="${images}states/WA.png" />', speech : 'Washington'},
        {visual : '<img class="state" src="${images}states/AK.png" />', speech : 'Alaska'},
        {visual : '<img class="state" src="${images}states/HI.png" />', speech : 'Hawaii'},
        {visual : '<img class="state" src="${images}states/OK.png" />', speech : 'Oklahoma'},
        {visual : '<img class="state" src="${images}states/UT.png" />', speech : 'Utah'},
        {visual : '<img class="state" src="${images}states/NM.png" />', speech : 'New Mexico'},
        {visual : '<img class="state" src="${images}states/AZ.png" />', speech : 'Arizona'},
        {visual : '<img class="state" src="${images}states/MO.png" />', speech : 'Missouri'},
        {visual : '<img class="state" src="${images}states/NJ.png" />', speech : 'New Jersey'},
        {visual : '<img class="state" src="${images}states/MN.png" />', speech : 'Minnesota'}
    ]
}