{
    GAME_TITLE : 'Spaceship!',
    // menu items
    NEW_GAME_ITEM : 'New Game',
    RESUME_GAME_ITEM : 'Resume Game',
    OPTIONS_ITEM : 'Options',
    SCORES_ITEM : 'Scores',
    NEWS_ITEM : 'News',
    CREDITS_ITEM : 'Credits',
    HELP_ITEM : 'Help',
    QUIT_GAME_ITEM : 'Quit',
    QUIT_TITLE : 'Really quit the game?',
    YES_QUIT_ITEM : 'Yes',
    NO_QUIT_ITEM : 'No',
    RESET_OPTIONS_ITEM : 'Reset Options',
    // difficulties
    DIFFICULTY_TITLE: 'Select a Difficulty',
    EASY_LEVEL : 'Easy',
    MEDIUM_LEVEL : 'Medium',
    HARD_LEVEL : 'Hard',
    // tiles
    HIDDEN_TILE : 'Hidden space',
    EMPTY_TILE : 'Empty space',
    AMMO_TILE : 'Empty ammo box',
    SHIELD_TILE : 'Empty shield charger',
    HINT_TILE : 'Dead sensor hint',
    WARP_TILE : 'Dead enemy warp',
    BOMB_TILE : 'Space mine shell',
    LEECH_TILE : 'Dead space leech',
    SHIP_TILE : 'Dead enemy ship',
    // intro messages
    INTRO_MESSAGE: 'Enemy ships sighted!',
    GOAL_MESSAGE: 'Destroy ${enemies} ship to win.',
    GOALS_MESSAGE: 'Destroy ${enemies} ships to win.',
    // change and status messages
    HIT_MESSAGE : 'You destroyed an enemy ship!', 
    MISS_MESSAGE : 'You missed!',
    HIT_REMAIN_MESSAGE : 'Destroy one more to win.',
    HITS_REMAIN_MESSAGE : 'Destroy ${enemies} more to win.',
    AMMO_MESSAGE : 'You found a box of ammo!',
    AMMOS_MESSAGE : 'You found ${ammo} boxes of ammo!',
    AMMO_REMAIN_MESSAGE : 'You have ${ammo} shot left.',
    AMMOS_REMAIN_MESSAGE : 'You have ${ammo} shots left.',
    SHIELD_MESSAGE : 'You found a shield!',
    SHIELDS_MESSAGE : 'You found ${shields} shields!',
    SHIELD_REMAIN_MESSAGE : 'You have ${shields} shield left.',
    SHIELDS_REMAIN_MESSAGE : 'You have ${shields} shields left.',    
    LEECH_MESSAGE : 'A space leech stole an ammo box!',
    LEECHES_MESSAGE : 'Space leeches stole ${ammo} ammo boxes!',
    BOMB_MESSAGE : 'A space mine destroyed a shield!',
    BOMBS_MESSAGE : 'Space mines destroyed ${shields} shields!', 
    HINT_MESSAGE : 'Enemy ship detected!',
    HINT_CELL_MESSAGE : 'Row ${row}, column ${column}.',
    WARP_MESSAGE : 'Enemy reinforcements warp-in!',
    // next action messages
    SHOT_MESSAGE: 'Prepare to fire!',
    MINIGAME_MESSAGE : 'Challenge time: ${challenge}!',
    // minigame messages
    AMMO_MINIGAME_MESSAGE : 'earn ammo',
    SHIELDS_MINIGAME_MESSAGE : 'charge your shields',
    BOMBS_MINIGAME_MESSAGE : 'avoid enemy fire',
    WARPS_MINIGAME_MESSAGE : 'stop enemy warps',
    WIN_MINIGAME_MESSAGE : 'You won the challenge!',
    LOSE_MINIGAME_MESSAGE : 'You lost the challenge!',
    WIN_AMMO_MESSAGE : 'You won a box of ammo.',
    WIN_AMMOS_MESSAGE : 'You won ${ammo} ammo boxes.',
    LOSE_AMMO_MESSAGE : 'You earned no ammo.',
    WIN_SHIELD_MESSAGE : 'Your ship charged a shield.',
    WIN_SHIELDS_MESSAGE : 'Your ship charged ${shields} shields.',
    LOSE_SHIELD_MESSAGE : 'Your shield charger failed.',
    LOSE_BOMB_MESSAGE : 'Enemy fire destroyed a shield.',
    LOSE_BOMBS_MESSAGE : 'Enemy fire destroyed ${shields} shields.',
    WIN_BOMB_MESSAGE : 'You avoided enemy fire.',
    LOSE_WARP_MESSAGE : 'An enemy ship appeared.',
    LOSE_WARPS_MESSAGE : 'A warp brought ${ships} enemy ships.',
    WIN_WARP_MESSAGE : 'You stopped enemy reinforcements.',
    // HUD
    HUD_SHIPS: 'Ships',
    HUD_SHIELDS : 'Shields',
    HUD_AMMO : 'Ammo boxes',
    // game outcome messages
    WIN_GAME_MESSAGES : ['Your enemies lie in ruin.',
                         'You won the game!',
                         'Congratulations!'],
    LOSE_GAME_MESSAGES : ["Your shields have failed.",
                          'The game is over.',
                          'Better luck next time!']
}